services:
  test:
    container_name: tactical_edge_test
    image: tactical_edge_test:latest
    env_file:
      - .test.env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: npm run test
    ports:
      - '${SERVER_NETWORK_PORT}:${SERVER_DOCKER_PORT}'
    networks:
      - tactical_edge_test_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true
  database:
    container_name: tactical_edge_test_database
    image: mongo:7.0.12
    env_file:
      - .test.env
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - '${DATABASE_NETWORK_PORT}:${DATABASE_DOCKER_PORT}'
    volumes:
      - database:/data/db
    networks:
      - tactical_edge_test_network

networks:
  tactical_edge_test_network:

volumes:
  database:
