services:
  ci:
    container_name: tactical_edge_ci
    image: tactical_edge_ci:latest
    env_file:
      - .test.env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: npm run ci
    ports:
      - '${SERVER_NETWORK_PORT}:${SERVER_DOCKER_PORT}'
    networks:
      - tactical_edge_ci_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  tactical_edge_ci_network:
