services:
  test:
    container_name: tactical_edge_test
    image: tactical_edge_test:latest
    env_file:
      - .test.env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    command: npm run test
    ports:
      - '${SERVER_NETWORK_PORT}:${SERVER_DOCKER_PORT}'
    networks:
      - tactical_edge_test_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  tactical_edge_test_network:
