name: CI

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - run: cp .ci.env .test.env

      - name: Run tests via Docker
        run: yarn docker:ci
